[project]
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "cantera-workshop"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cantera = ">=3.1.0,<4"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.1,<4"
pandas = ">=2.2.3,<3"
ipympl = ">=0.9.6,<0.10"
graphviz = ">=12.2.1,<13"
python-graphviz = ">=0.20.3,<0.21"
scipy = ">=1.15.2,<2"
jupytext = ">=1.16.7,<2"
